repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^vendor/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # Use the desired Prettier version
    hooks:
      - id: prettier
